repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              tests/.*|
              .*\.svg|
              .*\.yml|
              .*\.json
          )$
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-ast
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.md
            )$

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-cachetools==5.3.0.4
          - types-filelock==3.2.7
          - types-requests==2.30.0.0
          - types-tabulate==0.9.0.1
          - types-python-dateutil==2.8.19.10
          - pandas-stubs==2.0.1.230501
          - SQLAlchemy==2.0.7
          - wandb==0.15.2

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
